import express from 'express';
import authRoutes from "./auth.routes.js";
import userRoutes from "./user.routes.js";
import adminRoutes from "./admin.routes.js";
import scheduleRoutes from "./schedule.routes.js";
import availabilityRoutes from "./availability.routes.js";
import clockRoutes from "./clock.routes.js";
import shiftRoutes from "./shift.routes.js";
import coverageRoutes from "./coverage.routes.js";
import notificationRoutes from "./notifications.routes.js";
import skillRoutes from "./skills.routes.js";
import taskListItemRoutes from "./taskListItem.routes.js";
import taskListRoutes from "./taskList.routes.js";
import shiftSwapRequestRoutes from "./shiftSwapRequest.routes.js";
import timeOffRequestRoutes from "./timeOffRequest.routes.js";
import businessAreaRoutes from "./businessArea.routes.js";
import jobRoleRoutes from "./jobRole.routes.js";
import sessionRoutes from "./session.routes.js";

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/admin", adminRoutes);
router.use("/schedule", scheduleRoutes);
router.use("/availability", availabilityRoutes);
router.use("/clock", clockRoutes);
router.use("/shifts", shiftRoutes);
router.use("/coverage", coverageRoutes);
router.use("/notifications", notificationRoutes);
router.use("/skills", skillRoutes);
router.use("/taskListItem", taskListItemRoutes);
router.use("/taskList", taskListRoutes);
router.use("/shiftSwapRequests", shiftSwapRequestRoutes);
router.use("/timeOffRequests", timeOffRequestRoutes);
router.use("/business-areas", businessAreaRoutes);
router.use("/job-roles", jobRoleRoutes);
router.use("/sessions", sessionRoutes);

export default router;